In [1]:
# Hands-On Exercises
# Array Operations and Broadcasting:

# 1. Given a 3D array a with shape (2, 3, 4) and a 2D array b with shape (3, 4), perform element-wise multiplication between a and b using broadcasting.
# 2. Implement a function that takes two 2D arrays c and d with different shapes and performs element-wise operations (addition, subtraction, multiplication, 
# and division) between them using broadcasting. Handle the case where broadcasting is not possible.
# 3. Create a 2D array e with shape (5, 3) and a 1D array f with length 5. Compute the outer product of e and f using broadcasting.

# 1.
import numpy as np

a = np.random.rand(2, 3, 4)
b = np.random.rand(3, 4)
result = a * b
print(result)


[[[6.38365808e-02 2.85151651e-01 4.21798406e-04 2.37111346e-02]
  [5.17792762e-03 7.47418386e-02 4.28515767e-01 3.81074375e-02]
  [2.38992244e-01 1.35152296e-01 7.10019078e-01 4.49279361e-01]]

 [[1.27788362e-01 1.21545229e-01 8.48836322e-02 3.28679603e-01]
  [1.00134158e-01 5.20466266e-02 4.55795265e-01 8.92825689e-03]
  [5.63146954e-01 5.58793209e-02 1.73945204e-01 2.35598191e-01]]]


In [2]:
# 2.
def broadcast_operations(c, d):
    try:
        add_result = c + d
        sub_result = c - d
        mul_result = c * d
        div_result = c / d
        return add_result, sub_result, mul_result, div_result
    except ValueError as e:
        print(f"Broadcasting error: {e}")
        return None

c = np.random.rand(4, 5)
d = np.random.rand(1, 5)  
results = broadcast_operations(c, d)
if results:
    add_result, sub_result, mul_result, div_result = results
    print("Addition Result:\n", add_result)
    print("Subtraction Result:\n", sub_result)
    print("Multiplication Result:\n", mul_result)
    print("Division Result:\n", div_result)


Addition Result:
 [[0.71905405 0.49911537 1.2133302  1.49667251 0.65080306]
 [0.58499238 0.79431051 0.53328086 1.410963   0.7572514 ]
 [0.32488881 1.01831827 1.36646359 1.19827528 0.94258567]
 [0.60408493 0.79546673 1.12451659 1.77672748 1.34149179]]
Subtraction Result:
 [[ 0.57316538  0.29103862  0.40396557 -0.13163306 -0.52398429]
 [ 0.43910371  0.58623376 -0.27608377 -0.21734257 -0.41753595]
 [ 0.17900015  0.81024152  0.55709896 -0.4300303  -0.23220167]
 [ 0.45819627  0.58738998  0.31515196  0.1484219   0.16670445]]
Multiplication Result:
 [[0.04713004 0.04110317 0.3272455  0.55567534 0.03724627]
 [0.037351   0.07181479 0.05204156 0.4858947  0.09977335]
 [0.01837792 0.09512019 0.38921587 0.3127344  0.20863753]
 [0.0387437  0.07193508 0.2913042  0.78368287 0.44295246]]
Division Result:
 [[8.85757255 3.79741603 1.99822887 0.83831897 0.10795041]
 [7.01970981 6.6347839  0.31777653 0.73304449 0.28917187]
 [3.45392811 8.78791013 2.37663283 0.47180639 0.60469157]
 [7.28145121 6.64589724 1.

In [3]:
# 3.
e = np.random.rand(5, 3)
f = np.random.rand(5)

outer_product = e * f[:, np.newaxis]
print(outer_product)


[[0.39354049 0.49800519 0.5601814 ]
 [0.11080031 0.26073366 0.15441237]
 [0.23334877 0.64523689 0.66741609]
 [0.36762377 0.26556353 0.47526917]
 [0.46213707 0.18849667 0.0607584 ]]


In [4]:
# Indexing and Slicing:

# 1.Given a 3D array g with shape (4, 3, 2), extract every other element along the first and second dimensions, but keep all
# elements along the third dimension.
# 2.Create a function that takes a 2D array h and an array of row indices i and column indices j. The function should return a new array
# k where k[m, n] is the sum of the elements in h along the diagonal specified by i[m] and j[n].
# 3.Implement a function that takes a 2D array l and returns a new array m where each element in m is the product of the corresponding row
# and column means in l.

# 1.
g = np.random.rand(4, 3, 2)

# Extracting every other element along the first and second dimensions
sliced_g = g[::2, ::2, :]
print(sliced_g)


[[[0.20510262 0.30422858]
  [0.84159294 0.19118034]]

 [[0.43569264 0.4865267 ]
  [0.00627182 0.43050035]]]


In [5]:
# 2.
def diagonal_sum(h, i, j):
    k = np.array([h[i[m], j[n]] for m in range(len(i)) for n in range(len(j))]).reshape(len(i), len(j))
    return k

h = np.random.rand(5, 5)
i = np.array([0, 1, 2])
j = np.array([0, 1, 2])

k = diagonal_sum(h, i, j)
print(k)


[[0.79874263 0.35670253 0.2688028 ]
 [0.76746589 0.62832159 0.71372254]
 [0.32429557 0.38762995 0.35049396]]


In [6]:
# 3.
def row_col_mean_product(l):
    row_means = l.mean(axis=1)
    col_means = l.mean(axis=0)
    m = np.outer(row_means, col_means)
    return m

l = np.random.rand(4, 4)
m = row_col_mean_product(l)
print(m)


[[0.45909839 0.2403061  0.38964198 0.23154105]
 [0.35637889 0.18653958 0.30246278 0.17973564]
 [0.41440475 0.21691209 0.35170999 0.20900032]
 [0.46373158 0.24273126 0.39357423 0.23387775]]


In [7]:
# Array Manipulation:

# 1.Given a 2D array n with shape (4, 6), reshape it into a 3D array with shape (2, 2, 6) and then flatten it back to a 2D array with shape (4, 6).
# 2.Implement a function that takes a 2D array o and rolls it along the first axis by a specified number of positions. For example, if the input 
# array is [[1, 2, 3], [4, 5, 6]] and the number of positions is 1, the output should be [[4, 5, 6], [1, 2, 3]].
# 3.Create a function that takes a 2D array p and replaces all occurrences of a specified value x with the mean of the neighboring 
# elements (horizontally and vertically) in the array.

# 1.
n = np.random.rand(4, 6)

# Reshaping to (2, 2, 6)
reshaped_n = n.reshape(2, 2, 6)

# Flattening back to (4, 6)
flattened_n = reshaped_n.reshape(4, 6)
print(flattened_n)


[[0.09398853 0.94561786 0.32846486 0.27203687 0.22178744 0.18411933]
 [0.97343238 0.67038382 0.86396128 0.07160837 0.66369787 0.78360152]
 [0.76644824 0.50958258 0.00447362 0.27652093 0.14173625 0.24386767]
 [0.79876336 0.7434402  0.40800855 0.74304277 0.80166346 0.08189859]]


In [8]:
# 2.
def roll_array(o, positions):
    rolled_o = np.roll(o, shift=positions, axis=0)
    return rolled_o

o = np.array([[1, 2, 3], [4, 5, 6]])
positions = 1
rolled_o = roll_array(o, positions)
print(rolled_o)


[[4 5 6]
 [1 2 3]]


In [9]:
# 3.
def replace_with_mean(p, x):
    p = p.copy()
    rows, cols = p.shape
    for i in range(rows):
        for j in range(cols):
            if p[i, j] == x:
                neighbors = []
                if i > 0:
                    neighbors.append(p[i-1, j])
                if i < rows-1:
                    neighbors.append(p[i+1, j])
                if j > 0:
                    neighbors.append(p[i, j-1])
                if j < cols-1:
                    neighbors.append(p[i, j+1])
                p[i, j] = np.mean(neighbors) if neighbors else p[i, j]
    return p

p = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = 5
new_p = replace_with_mean(p, x)
print(new_p)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
